[package]
name = "lexy-web"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
exact-logic = { path = "../../../../exact2/logic" }
exact-web = { path = "../../../../exact2/host/web" }
exact-web-capabilities = { path = "../../../../exact2/host/web-capabilities" }
exact-js-web = { path = "../../../../exact2/js/web" }

[build-dependencies]
exact-js-bake = { path = "../../../../exact2/js/bake" }
