#!/usr/bin/env bun
// lexy's commands, run with the exact2 checkout named by EXACT2
// (default ../../../exact2). Generated by `exact new`; `bun exact.mjs update` rewrites
// this file, the crates.io patches, the toolchain and the exact2 dependency paths.
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';

const EXACT2 = resolve(import.meta.dir, process.env.EXACT2 ?? "../../../exact2");
const verbs = {
  web: ['host/web/dev.mjs', '--app', 'lexy'],
  'web-build': ['host/web/build.mjs', 'lexy-web', '--wasm'],
  ios: ['host/apple/build.mjs', '--ios', 'lexy-apple'],
  mac: ['host/apple/build.mjs', 'lexy-apple'],
  update: ['scripts/exact.mjs', 'new', import.meta.dir, '--update'],
};
const [verb, ...rest] = process.argv.slice(2);
if (!verbs[verb]) {
  console.error(`Usage: bun exact.mjs <${Object.keys(verbs).join('|')}> [arguments for that script]`);
  process.exit(2);
}
const [script, ...args] = verbs[verb];
const result = spawnSync(process.execPath, [resolve(EXACT2, script), ...args, ...rest], {
  stdio: 'inherit',
  env: { ...process.env, EXACT_APP_DIR: import.meta.dir },
});
process.exit(result.status ?? 1);
